doctrine:
  dbal:
    driver: pdo_mysql
    host: mysql
    port: 3306
    dbname: app_db
    user: user
    password: password
    charset: utf8mb4
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true